<?php

namespace App\Form;

use App\Entity\Contact;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ContactType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        //parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
        $builder
            ->add('firstName',TextType::class,['label'=>'Prénom'])
            ->add('lastName',TextType::class,['label'=>'Nom'])
            ->add('email',EmailType::class,['label'=>'Email'])
            ->add('message',TextareaType::class,['label'=>'Message']);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        //parent::configureOptions($resolver); // TODO: Change the autogenerated stub
        $resolver->setDefaults([
            'data_class' => Contact::class,
        ]);
    }
}